#!/bin/bash
echo " "
echo "Starting... "
echo " " 

echo "IP's inside the network:"
for ip in {1..254}

do

ping -c 1 192.168.88.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" | sort -n &

done

echo " "
echo "done."

exit
